apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-rhtap-devfile-multi-component-ghyg
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ryzs-tenant/mc-two-scenarios/devfile-sample-python-basic-rhtap-devfile-multi-component-ghyg@sha256:52ea565dd01e23dd3f96d213ac818d749fe24dec2acf923ecb3ebf779bb73006
        name: my-python
        resources: {}
status: {}
